[[Mingw]]
arch = "x86_64"
git-tree-sha1 = "28ff481f47086735fbe8f5787b642927264f236c"
os = "windows"

    [[Mingw.download]]
    sha256 = "4e52cec11894a29478e90a00f43514146161438ee8c511aea266ad4b4d6a33cb"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.3-GCCBootstrap/Mingw-v11.0.3-x86_64-w64-mingw32.tar.gz"
[[Mingw]]
arch = "i686"
git-tree-sha1 = "6d253b882ffc41a341ef6c1b56c1df6041cf4098"
os = "windows"

    [[Mingw.download]]
    sha256 = "bcd4be967248213be83cb579088cab216018670bddf68c243230f4b6865e8680"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.3-GCCBootstrap/Mingw-v11.0.3-i686-w64-mingw32.tar.gz"

[[Mingw-build_log]]
arch = "x86_64"
git-tree-sha1 = "aae86b9d1896aeae776f63bc4e31debbc149543c"
lazy = true
os = "windows"

    [[Mingw-build_log.download]]
    sha256 = "0bdf9f7273e257b54ba1d877585ed7695ca8c40ed84abdc2eb94f8c2f9f1fa89"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.3-GCCBootstrap/Mingw-build_log-v11.0.3-x86_64-w64-mingw32.tar.gz"
[[Mingw-build_log]]
arch = "i686"
git-tree-sha1 = "4d4251afdcd195a970304a65b80220223b04e2fc"
lazy = true
os = "windows"

    [[Mingw-build_log.download]]
    sha256 = "3602f807259b3df3c1602c94eb0cd0834ca30926f6d30e8b36d91b24f177145b"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.3-GCCBootstrap/Mingw-build_log-v11.0.3-i686-w64-mingw32.tar.gz"

[[Mingw-extract_log]]
arch = "x86_64"
git-tree-sha1 = "203e17f155bf729fdd4da6ff193d12d6966c22ad"
lazy = true
os = "windows"

    [[Mingw-extract_log.download]]
    sha256 = "361a01b5c24e5d23f2724480918f95e6ac300d2499d0f438e7dbd25083ae8b58"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.3-GCCBootstrap/Mingw-extract_log-v11.0.3-x86_64-w64-mingw32.tar.gz"
[[Mingw-extract_log]]
arch = "i686"
git-tree-sha1 = "0a5eebe550044a436bf785ed999160fbf855a6b6"
lazy = true
os = "windows"

    [[Mingw-extract_log.download]]
    sha256 = "c0d0525d8bbe85d514b04c3005aee17f9c67056ebec75d610bab2fcf28767077"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.3-GCCBootstrap/Mingw-extract_log-v11.0.3-i686-w64-mingw32.tar.gz"
