[[Mingw]]
arch = "x86_64"
git-tree-sha1 = "d37c1039397200e76891dc69162ff4a0f0f3da8e"
os = "windows"

    [[Mingw.download]]
    sha256 = "c3af0502cecc1cdd4739e023fc5d75c4728f5ff51a792da635d681466bc2d017"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1/Mingw-v11.0.1-x86_64-w64-mingw32.tar.gz"
[[Mingw]]
arch = "i686"
git-tree-sha1 = "bea992bdad2b10621d96ad0637da9d5b585f2454"
os = "windows"

    [[Mingw.download]]
    sha256 = "f62c9149fc4344e3d7f3335045b8cae3cbe2721cdc796a2f531e42f93a751dce"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1/Mingw-v11.0.1-i686-w64-mingw32.tar.gz"

[[Mingw-build_log]]
arch = "x86_64"
git-tree-sha1 = "ed6cabf420d8474db88efd5dfcea8b63fc7b5094"
lazy = true
os = "windows"

    [[Mingw-build_log.download]]
    sha256 = "9ebf71a170d9d156fe58c1100b2148ed96e9fb5c94032bc60b4fd620cdd7016b"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1/Mingw-build_log-v11.0.1-x86_64-w64-mingw32.tar.gz"
[[Mingw-build_log]]
arch = "i686"
git-tree-sha1 = "ba0b83d921504101229c4ffb20c44915d807df9e"
lazy = true
os = "windows"

    [[Mingw-build_log.download]]
    sha256 = "ce9fbe5038aac4d7e110e54fd38155e13a842a58950b22b377f502bad3e8f39b"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1/Mingw-build_log-v11.0.1-i686-w64-mingw32.tar.gz"

[[Mingw-extract_log]]
arch = "x86_64"
git-tree-sha1 = "b6f3c336911fbb956d8423d3e67d8589749b56af"
lazy = true
os = "windows"

    [[Mingw-extract_log.download]]
    sha256 = "7413df60e35186e2beee494cadd5c53088c3787438d5d7a1efbf4ba1550ca45c"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1/Mingw-extract_log-v11.0.1-x86_64-w64-mingw32.tar.gz"
[[Mingw-extract_log]]
arch = "i686"
git-tree-sha1 = "c9b76bcfa1e89f4a28962a8ee05d2ade5a39719d"
lazy = true
os = "windows"

    [[Mingw-extract_log.download]]
    sha256 = "3c7cfdd78dac493d5ee640ae15445b5cf8dc2cf91ecefb530d612a74a8fc4953"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1/Mingw-extract_log-v11.0.1-i686-w64-mingw32.tar.gz"
