[[Mingw]]
arch = "x86_64"
git-tree-sha1 = "a55fbc2879d423d64773f3ef5abf1e4b13d9f6a0"
os = "windows"

    [[Mingw.download]]
    sha256 = "628e7d79ba496097ef2244ba0b976b725c86469c167652777690025e9215c089"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1-GCCBootstrap-x86_64-linux-gnu/Mingw-v11.0.1-x86_64-w64-mingw32.tar.gz"
[[Mingw]]
arch = "i686"
git-tree-sha1 = "740df03d602d98c57026a47c90410a6a494729c5"
os = "windows"

    [[Mingw.download]]
    sha256 = "1c0c47d24120fd195507d69a3d630d65ebfbdf3b09ec534f06e42d0fcfbe377a"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1-GCCBootstrap-x86_64-linux-gnu/Mingw-v11.0.1-i686-w64-mingw32.tar.gz"

[[Mingw-build_log]]
arch = "x86_64"
git-tree-sha1 = "3237d7006147e905ad5eb3aa38de9872f69f7117"
lazy = true
os = "windows"

    [[Mingw-build_log.download]]
    sha256 = "8929a780f3695514b47230f4911ce73d464714b0f2d2629c573ec5de01ac41f1"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1-GCCBootstrap-x86_64-linux-gnu/Mingw-build_log-v11.0.1-x86_64-w64-mingw32.tar.gz"
[[Mingw-build_log]]
arch = "i686"
git-tree-sha1 = "d8b35da9d58a61a55c0d21d42a56d6947311964c"
lazy = true
os = "windows"

    [[Mingw-build_log.download]]
    sha256 = "9a1cda95bd21ca95df3f665f845b513f13cdd8d70111ae2c53264c8694834a44"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1-GCCBootstrap-x86_64-linux-gnu/Mingw-build_log-v11.0.1-i686-w64-mingw32.tar.gz"

[[Mingw-extract_log]]
arch = "x86_64"
git-tree-sha1 = "f4f8cb17ff2d6de15c73869609fdc472fbfab90c"
lazy = true
os = "windows"

    [[Mingw-extract_log.download]]
    sha256 = "63d7e8bacf9b0461534d420e3b23a6768c081232783c541a7b58af39ccc5366f"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1-GCCBootstrap-x86_64-linux-gnu/Mingw-extract_log-v11.0.1-x86_64-w64-mingw32.tar.gz"
[[Mingw-extract_log]]
arch = "i686"
git-tree-sha1 = "b61c7d0a5d51a1cff09be45528ef83952d78123b"
lazy = true
os = "windows"

    [[Mingw-extract_log.download]]
    sha256 = "fe7d054ecd8c9aa9aeefd677166963bcc900b50eb8c6ac331f42a0aca545d38b"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1-GCCBootstrap-x86_64-linux-gnu/Mingw-extract_log-v11.0.1-i686-w64-mingw32.tar.gz"
