[[Mingw]]
arch = "x86_64"
git-tree-sha1 = "b8458e53c62d86a2b2788b0fbf52c410e57f65d9"
os = "windows"

    [[Mingw.download]]
    sha256 = "f4ed2c84c7eb8333fac78cd74a51daea4110494a8b1c9bb36d61571c50d7efcb"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1-GCCBootstrap-x86_64-linux-gnu/Mingw-v11.0.1-x86_64-w64-mingw32.tar.gz"
[[Mingw]]
arch = "i686"
git-tree-sha1 = "a9d422de4ffdedb83ceb0848fe5a1ccfa47f88ad"
os = "windows"

    [[Mingw.download]]
    sha256 = "e78e2ca804f516a49e9895729de6b85fd43bb01af2a1035a60733e086dd38de9"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1-GCCBootstrap-x86_64-linux-gnu/Mingw-v11.0.1-i686-w64-mingw32.tar.gz"

[[Mingw-build_log]]
arch = "x86_64"
git-tree-sha1 = "eb2194e976b3145f9fb0aa60b859c4f8a82cd1d6"
lazy = true
os = "windows"

    [[Mingw-build_log.download]]
    sha256 = "a0bbb5b392d54430b4466376b2bdb097a991b68f2bf0cf6e112619eaa388aaca"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1-GCCBootstrap-x86_64-linux-gnu/Mingw-build_log-v11.0.1-x86_64-w64-mingw32.tar.gz"
[[Mingw-build_log]]
arch = "i686"
git-tree-sha1 = "79ca9220ef15573bd16ca4e3cce8f6781f456bad"
lazy = true
os = "windows"

    [[Mingw-build_log.download]]
    sha256 = "330ccbf138671745502342ceab44099a1cd2fc380eb815068dfe2e940b4aaa82"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1-GCCBootstrap-x86_64-linux-gnu/Mingw-build_log-v11.0.1-i686-w64-mingw32.tar.gz"

[[Mingw-extract_log]]
arch = "x86_64"
git-tree-sha1 = "e18c448c95ae85d2534f46b382e1916cd3628deb"
lazy = true
os = "windows"

    [[Mingw-extract_log.download]]
    sha256 = "4dcfd9b2ac1f787996b2eebc3ba51b810be1bea42eced2ee2bd779dc5ed04a6c"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1-GCCBootstrap-x86_64-linux-gnu/Mingw-extract_log-v11.0.1-x86_64-w64-mingw32.tar.gz"
[[Mingw-extract_log]]
arch = "i686"
git-tree-sha1 = "65c5fd624bc73a8a22e8e244eaf29284f50fa385"
lazy = true
os = "windows"

    [[Mingw-extract_log.download]]
    sha256 = "83c4fea5b90dba1db893358c1842bd16e1558ff6d4a9c310c0a6cb22a5a934fe"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1-GCCBootstrap-x86_64-linux-gnu/Mingw-extract_log-v11.0.1-i686-w64-mingw32.tar.gz"
