[[Mingw]]
arch = "x86_64"
git-tree-sha1 = "c8468af536625f1e1280f5d2c4d0db6a9dc2b20a"
os = "windows"

    [[Mingw.download]]
    sha256 = "bd913e2e5c4d022ca10d219588b099bdd2552d1c149c534d33cb860616d97565"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1/Mingw-v11.0.1-x86_64-w64-mingw32.tar.gz"
[[Mingw]]
arch = "i686"
git-tree-sha1 = "bc55af6cde443ca6e5d4abb2a06641c574edff8b"
os = "windows"

    [[Mingw.download]]
    sha256 = "fca06f6a0794b0c965c3d41d9cfb8efcb4cd791d7032a39d76907d8a755da43d"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1/Mingw-v11.0.1-i686-w64-mingw32.tar.gz"

[[Mingw-build_log]]
arch = "x86_64"
git-tree-sha1 = "fe77a02a83237323dc8e0ee34f277d7a970c8d66"
lazy = true
os = "windows"

    [[Mingw-build_log.download]]
    sha256 = "a3da17230386b1226f93fab0878e0215bede88bafd3e0d5a4bfa400da282d7ef"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1/Mingw-build_log-v11.0.1-x86_64-w64-mingw32.tar.gz"
[[Mingw-build_log]]
arch = "i686"
git-tree-sha1 = "0b1bd9f1124e52f05b1bc7c2623cb3f6d39ce23e"
lazy = true
os = "windows"

    [[Mingw-build_log.download]]
    sha256 = "51fd75bc35416073c2cb678e85a57b5f64eb6b29ecd0ba17da3aec3b71dd8a97"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1/Mingw-build_log-v11.0.1-i686-w64-mingw32.tar.gz"

[[Mingw-extract_log]]
arch = "x86_64"
git-tree-sha1 = "ccbf792862dae193c602de1d714065ea6406fa0e"
lazy = true
os = "windows"

    [[Mingw-extract_log.download]]
    sha256 = "06be4aa25e79d06fbe0958212ce3e05db18ba5d8c51eddd052b7fbd04572a029"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1/Mingw-extract_log-v11.0.1-x86_64-w64-mingw32.tar.gz"
[[Mingw-extract_log]]
arch = "i686"
git-tree-sha1 = "36f3cb79b4c1b09661f4d40fa80a30e4a49cbdd2"
lazy = true
os = "windows"

    [[Mingw-extract_log.download]]
    sha256 = "59ad5eb7fc5aebe0a8e446c5fbd33043453f8c2fcb51d1501633f13461323886"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1/Mingw-extract_log-v11.0.1-i686-w64-mingw32.tar.gz"
