[[Mingw]]
arch = "x86_64"
git-tree-sha1 = "1cd2d567db4c220502eda225f7a5146d38ba77a2"
os = "windows"

    [[Mingw.download]]
    sha256 = "14d6f1662b367db80544438f4cab7fb0cdb0b343c2c48dff09ba5a459419677b"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1/Mingw-v11.0.1-x86_64-w64-mingw32.tar.gz"
[[Mingw]]
arch = "i686"
git-tree-sha1 = "75a9bc7b4cfb78593c864b85f5530cbee8ae4022"
os = "windows"

    [[Mingw.download]]
    sha256 = "66d002d52abfb61aa201c2d3e3285b89dfe9de04a152803ed9e3a7a72d86232c"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1/Mingw-v11.0.1-i686-w64-mingw32.tar.gz"

[[Mingw-build_log]]
arch = "x86_64"
git-tree-sha1 = "8c03ade753ee49331e07d83f1531dbcdab261a2e"
lazy = true
os = "windows"

    [[Mingw-build_log.download]]
    sha256 = "1f4ec350db5db2e6bc903ee7a84d621d7348d0c9f8fa6fdb4c1a19ab4cc2b2bf"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1/Mingw-build_log-v11.0.1-x86_64-w64-mingw32.tar.gz"
[[Mingw-build_log]]
arch = "i686"
git-tree-sha1 = "b547130c185bf62b2e5f2ff4f00d01fda91d643d"
lazy = true
os = "windows"

    [[Mingw-build_log.download]]
    sha256 = "b7c1be2ccc855bb3c13526b468a2337f1d70db3e1d4cea3e24741958ced29fbf"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1/Mingw-build_log-v11.0.1-i686-w64-mingw32.tar.gz"

[[Mingw-extract_log]]
arch = "x86_64"
git-tree-sha1 = "b39a0743d741ee6a9624eebc837748c12c021f40"
lazy = true
os = "windows"

    [[Mingw-extract_log.download]]
    sha256 = "d99acff24d6e35b9e315ddefcbedb25fc4b17686c554a1a9aa669fa5a5cd80da"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1/Mingw-extract_log-v11.0.1-x86_64-w64-mingw32.tar.gz"
[[Mingw-extract_log]]
arch = "i686"
git-tree-sha1 = "41113a7f930b7b1674d6c4873c171647f0766835"
lazy = true
os = "windows"

    [[Mingw-extract_log.download]]
    sha256 = "8ff75b8b7b8dc70517b6c323f9b8887e86749ef4b5e0e4047f43a7ecbd234779"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1/Mingw-extract_log-v11.0.1-i686-w64-mingw32.tar.gz"
