[[Mingw]]
arch = "x86_64"
git-tree-sha1 = "dba543a07ac4f2a447a13e43463762080474e245"
os = "windows"

    [[Mingw.download]]
    sha256 = "5fa7d0ae9e9b719483c2a5f59edfb796742338daf4558f2745c932c7cd302f48"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1-GCCBootstrap-x86_64-linux-gnu/Mingw-v11.0.1-x86_64-w64-mingw32.tar.gz"
[[Mingw]]
arch = "i686"
git-tree-sha1 = "7f29284e5c17ec4877372e6284077062b5f5ec8e"
os = "windows"

    [[Mingw.download]]
    sha256 = "7221f677bfd1ff19d747c42b1db98f25724fa7d2ad8bd29a9cd77077cd77aadd"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1-GCCBootstrap-x86_64-linux-gnu/Mingw-v11.0.1-i686-w64-mingw32.tar.gz"

[[Mingw-build_log]]
arch = "x86_64"
git-tree-sha1 = "8fa140dec3c89d78d0ea8e75dd9ecb6be313b474"
lazy = true
os = "windows"

    [[Mingw-build_log.download]]
    sha256 = "b6d763274e1165552c065c7ed74110bdd86930f40c3ef33b3b1610f152810719"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1-GCCBootstrap-x86_64-linux-gnu/Mingw-build_log-v11.0.1-x86_64-w64-mingw32.tar.gz"
[[Mingw-build_log]]
arch = "i686"
git-tree-sha1 = "712f96c8d333c9116216f5911b707c9447281bd6"
lazy = true
os = "windows"

    [[Mingw-build_log.download]]
    sha256 = "ccc74271d818f4fc5289c1e6197d1233cb94c4e2e283bf7cf8f1d12ec2e3764d"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1-GCCBootstrap-x86_64-linux-gnu/Mingw-build_log-v11.0.1-i686-w64-mingw32.tar.gz"

[[Mingw-extract_log]]
arch = "x86_64"
git-tree-sha1 = "51f4c126d124a925f257ad97f5d7880cd9dff1d9"
lazy = true
os = "windows"

    [[Mingw-extract_log.download]]
    sha256 = "ae71e3fddcd0f4b80707aebd05c264d44b715ff4c1afffd9be93359a081b63b4"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1-GCCBootstrap-x86_64-linux-gnu/Mingw-extract_log-v11.0.1-x86_64-w64-mingw32.tar.gz"
[[Mingw-extract_log]]
arch = "i686"
git-tree-sha1 = "b64e9bafa0be20948e91dd8e8ae9433688fad904"
lazy = true
os = "windows"

    [[Mingw-extract_log.download]]
    sha256 = "f7112ccdcd130b95fedaf119019146e0068fcc2a380eb94672f1ef0b8a7f2801"
    url = "https://github.com/staticfloat/Mingw_jll.jl/releases/download/v11.0.1-GCCBootstrap-x86_64-linux-gnu/Mingw-extract_log-v11.0.1-i686-w64-mingw32.tar.gz"
